### ISSUE TITLE
Can't install @babel/preser-env

### ISSUE THREAD

**Issue by achillis2** [eric-liclair/Django-React-Integration#1]
Do you have any ideas on how to fix the following error? Thanks

$ yarn add @babel/core @babel/preset-react @babel/preser-env --dev
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@babel%2fpreser-env: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/dli/projects/nexant/djreact/Django-React-Integration/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by eric-liclair** [comment]
probably a typing error.
Following should work
`$ yarn add @babel/core @babel/preset-react @babel/preset-env --dev`

If you notice, it should be @babel/preset-env and not preser-env

**Comment by achillis2** [comment]
Thanks. The problem is fixed. You may want to fix the typo in your post at medium.

**Comment by EricLiclair** [comment]
done. Thanx for the update though.
👍🏻
